name: Deploy Frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build-prod:t
        env:
          NX_CLOUD: 'false'  # Explicitly disable Nx Cloud
          NX_NO_CLOUD: 'true'  # todo needed, check other

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.HETZNER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/deploy_key" \
            dist/apps/tahatime/browser/ \
            ubuntu@${{ secrets.HETZNER_IP }}:/opt/tahatime/frontend/
